name: GitHub Advanced Security Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  advanced-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GitHub Advanced Security scan
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
